# used for to determine database engine
# will be used for the factory to determine which function to invoke
# connection details are provided below
dbms: mssql

# connection details passed to a specific implementation in './db/connector' based on the specified dbms
db-connection:
  host:
  username:
  password:
  schema:
  db: order_db_unif

# specifies which executor to use to execute generated queries and return runtime information about joins
executor: mssql-join-breakdown-xml
# config which will be passed to the above specified executor
executor-config:

# specifies a setup and teardown logic once the db engine connected. can be used to set log levels or join order forcing
db-setup:
# config which will be passed to the above specified db-setup functions
db-setup-config:

# specifes an sql generator to create a specific sql statement based on an abstract query
sql-creator: mssql-force-order
# config which will be passed to the above specified sql-generator for custom config
sql-creator-config:

# specifies which reinforcement learning approach is used
environment: luc-default
# config which will passed to the specified environment for custom setup etc
environment-config:

# specifies which query generator is used to create logical queries which ultimately will be passed to the environment
# / reinforcement learning algorithm to train/eval
query-generator: random-generator

query-generator-config:
  seed: 123





