# !! IF SET TO TRUE RELEO WILL EXECUTE EVERY POSSIBLE QUERY PLAN FOR EVERY LOGICAL QUERY IN THE TEST-SET !!
create-testset-reference: false

# config values which are provided to every sub-system
global:
  log-location: ./runs
  random-seed: 123


# used for to determine database engine
# will be used for the factory to determine which function to invoke
# connection details are provided below
dbms: mssql

# connection details passed to a specific implementation in './db/connector' based on the specified dbms
db-connection:
  host: localhost
  username: SA
  password: 
  schema: dbo
  db: order_db_non_unif
  # sql server default port ist 1433. 5434 is for my local docker image
  port: 5434
  driver: {ODBC Driver 13 for SQL Server}


# defines which creator is used to represent the database schema internally
schema-creator: definition-file
# config which will be passed to the specified schema-creator
schema-creator-config:
  category:
  order_details:
    joins:
      - source-column: order_id
        referred-table: order
        referred-column: id
      - source-column: product_id
        referred-table: product
        referred-column: id
  product:
    joins:
      - source-column: subcategory_id
        referred-table: subcategory
        referred-column: id
  subcategory:
    joins:
      - source-column: category_id
        referred-table: category
        referred-column: id
  customer:
  order:
    joins:
      - source-column: customer_id
        referred-table: customer
        referred-column: id
      - source-column: deliverer_id
        referred-table: deliverer
        referred-column: id
      - source-column: discount_id
        referred-table: discount
        referred-column: id
  deliverer:
  discount:

# specifies which executor to use to execute generated queries and return runtime information about joins
executor: mssql-join-breakdown-xml
# config which will be passed to the above specified executor
executor-config:

# specifies a setup and teardown logic once the db engine connected. can be used to set log levels or join order forcing
db-setup:
# config which will be passed to the above specified db-setup functions
db-setup-config:

# specifes an sql generator to create a specific sql statement based on an abstract query
sql-creator: mssql-force-order
# config which will be passed to the above specified sql-generator for custom config
sql-creator-config:

# specifies which reinforcement learning approach is used
environment: one-hot-history
# config which will passed to the specified environment for custom setup etc
environment-config:
  random-seed: 123
#  max-joins: 8

# specifies the rl agent to train and use for predictions
agent: dqn-default
# config which will be passed to the specified environment for custom setup etc
agent-config:
  environmet-name: rl_joinorder
  environment-continuous: false
  episodes: 300
  epsilon-initial: 1.0
  epsilon-min: 0.03
  epsilon-decay: 0.985
  gamma: 0.9
  tau: 0.1
  synchronize_networks_every: 5
  batch-size: 32
  learning-rate: 0.003
  layers:
    1:
      units: 64
      activation: relu
    2:
      units: 64
      activation: relu
    3:
      units: 16
      activation: relu
  output-activation: linear
  loss: huber_loss
  optimizer: adam
  replay-buffer-size: 512
  min-experiences-to-train: 32
  checkpoint-period: 20
  wandb-team-name: releo_zhaw
  wandb-group-name: debug
  wandb-project-name: dqn-default
  broken-buffer: false

# specifies which query generator is used to create logical queries which ultimately will be passed to the environment
# / reinforcement learning algorithm to train/eval
query-generator: train-split-random-generator

query-generator-config:
  trainset-location: ./src/query_generator/query_sets/train_set.csv
  testset-location: ./src/query_generator/query_sets/test_set.csv










