# used for to determine database engine
# will be used for the factory to determine which function to invoke
# connection details are provided below
dbms: mssql

# connection details passed to a specific implementation in './db/connector' based on the specified dbms
db-connection:
  host:
  username:
  password:
  schema:
  db: order_db_non_unif


# defines which creator is used to represent the database schema internally
schema-creator: autocreate
# config which will be passed to the specified schema-creator
schema-creator-config:

# specifies which executor to use to execute generated queries and return runtime information about joins
executor: mssql-join-breakdown-xml
# config which will be passed to the above specified executor
executor-config:

# specifies a setup and teardown logic once the db engine connected. can be used to set log levels or join order forcing
db-setup:
# config which will be passed to the above specified db-setup functions
db-setup-config:

# specifes an sql generator to create a specific sql statement based on an abstract query
sql-creator: mssql-force-order
# config which will be passed to the above specified sql-generator for custom config
sql-creator-config:

# specifies which reinforcement learning approach is used
environment: one-hot-history
# config which will passed to the specified environment for custom setup etc
environment-config:
  random-seed: 123
#  max-joins: 8

# specifies the rl agent to train and use for predictions
agent: dqn-default
# config which will be passed to the specified environment for custom setup etc
agent-config:
  environmet-name: rl_joinorder
  environment-continuous: false
  episodes: 300
  epsilon-initial: 1.0
  epsilon-min: 0.03
  epsilon-decay: 0.985
  gamma: 0.9
  tau: 0.1
  batch-size: 32
  learning-rate: 0.003
  layers:
    1:
      units: 64
      activation: relu
    2:
      units: 64
      activation: relu
    3:
      units: 16
      activation: relu
  output-activation: linear
  loss: huber_loss
  optimizer: adam
  replay-buffer-size: 512
  min-experiences-to-train: 32
  checkpoint-period: 20
  wandb-group-name: debug
  wandb-project-name: rl-joinorder-luc
  broken-buffer: false

# specifies which query generator is used to create logical queries which ultimately will be passed to the environment
# / reinforcement learning algorithm to train/eval
query-generator: random-generator

query-generator-config:
  seed: 123
  min-tables: 3
  max-tables: 8









