# !! IF SET TO TRUE RELEO WILL EXECUTE EVERY POSSIBLE QUERY PLAN FOR EVERY LOGICAL QUERY IN THE TEST-SET !!
create-testset-reference: false

# config values which are provided to every sub-system
global:
  log-location: ./runs/tpch/mssql
  # this will initialize random and np.random globally. One of the consequences is, that the keras models
  # will have the same initial weights
  random-seed: 123


# used for to determine database engine
# will be used for the factory to determine which function to invoke
# connection details are provided below
dbms: mssql

# connection details passed to a specific implementation in './db/connector' based on the specified dbms
db-connection:
  host: localhost
  username: SA
  password: zhaw2021_mssql
  schema: dbo
  db: tpc-h-1
  port: 5434
  driver: ODBC Driver 17 for SQL Server

# defines which creator is used to represent the database schema internally
schema-creator: definition-file
# config which will be passed to the specified schema-creator
schema-creator-config:
  part:
    joins:
      - source-column: p_partkey
        referred-table: partsupp
        referred-column: ps_partkey
  region:
    joins:
      - source-column: r_regionkey
        referred-table: nation
        referred-column: n_regionkey
  nation:
    joins:
      - source-column: n_nationkey
        referred-table: supplier
        referred-column: s_nationkey
      - source-column: n_nationkey
        referred-table: customer
        referred-column: c_nationkey
  supplier:
    joins:
      - source-column: s_suppkey
        referred-table: partsupp
        referred-column: ps_suppkey
  customer:
    joins:
      - source-column: c_custkey
        referred-table: orders
        referred-column: o_custkey
  partsupp:
    joins:
      - source-column: ps_partkey
        referred-table: lineitem
        referred-column: l_partkey
      - source-column: ps_suppkey
        referred-table: lineitem
        referred-column: l_suppkey
  orders:
    joins:
      - source-column: o_orderkey
        referred-table: lineitem
        referred-column: l_orderkey
  lineitem:

# specifies which executor to use to execute generated queries and return runtime information about joins
executor: mssql-join-breakdown-xml
# config which will be passed to the above specified executor
executor-config:

# specifies a setup and teardown logic once the db engine connected. can be used to set log levels or join order forcing
db-setup:
# config which will be passed to the above specified db-setup functions
db-setup-config:

# specifies an sql generator to create a specific sql statement based on an abstract query
sql-creator: mssql-force-order
# config which will be passed to the above specified sql-generator for custom config
sql-creator-config:

# specifies which reinforcement learning approach is used
environment: one-hot-history
# config which will passed to the specified environment for custom setup etc
environment-config:
  random-seed: 123
#  max-joins: 8

# specifies the rl agent to train and use for predictions
agent: dqn-default
# config which will be passed to the specified environment for custom setup etc
agent-config:
  environmet-name: rl_joinorder
  environment-continuous: false
  episodes: 200
  epsilon-initial: 1.0
  epsilon-min: 0.03
  epsilon-decay: 0.981
  gamma: 0.9
  tau: 0.1
  synchronize_networks_every: 2
  batch-size: 32
  learning-rate: 0.005
  layers:
    1:
      units: 32
      activation: relu
    2:
      units: 32
      activation: relu
    3:
      units: 16
      activation: relu
  output-activation: linear
  loss: huber_loss
  optimizer: adam
  replay-buffer-size: 256
  min-experiences-to-train: 32
  checkpoint-period: 9999
  wandb-team-name: releo_zhaw
  wandb-group-name: robin-local-mssql-tpc-h
  wandb-project-name: dqn-default
  broken-buffer: false
  epsilon-random-seed: 123
  sampling-random-seed: 123
  target-model-switch-interval: 5
  evaluation-interval: 7

# specifies which query generator is used to create logical queries which ultimately will be passed to the environment
# / reinforcement learning algorithm to train/eval
query-generator: train-split-random-generator

query-generator-config:
  trainset-location: ./query_generator/query_sets/tpc-h/train_set.csv
  testset-location: ./query_generator/query_sets/tpc-h/test_set.csv
#  random-seed: 123





